version: '2.2'
## We using version `2.2` because version `3` does not support cpu\mem limits for non swarm mode.
## https://github.com/docker/compose/issues/4513

services:
  cups:
    container_name: cups
    build: ./
    restart: always
    env_file:
      - .env
    ports:
      - "631:631/tcp"
      - "631:631/udp"
      - "10000-10100"
      - "6566:6566"
    volumes:
      - driver:/usr/share/hplip/data
      - ./data/logs:/var/log/cups
      - ./data/spool:/var/spool/cups
      - ./data/cache:/var/cache/cups
      - /var/run/dbus:/var/run/dbus
    privileged: true
    sysctls:
    - net.ipv6.conf.all.disable_ipv6=1

volumes:
    driver: